import { globalIgnores } from 'eslint/config'
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript'
import pluginVue from 'eslint-plugin-vue'
import pluginOxlint from 'eslint-plugin-oxlint'
import skipFormatting from 'eslint-config-prettier/flat'

// To allow more languages other than `ts` in `.vue` files, uncomment the following lines:
// import { configureVueProject } from '@vue/eslint-config-typescript'
// configureVueProject({ scriptLangs: ['ts', 'tsx'] })
// More info at https://github.com/vuejs/eslint-config-typescript/#advanced-setup

export default defineConfigWithVueTs(
  {
    name: 'app/files-to-lint',
    files: ['**/*.{vue,ts,mts,tsx}'],
  },

  globalIgnores([
    '**/dist/**',
    '**/dist-ssr/**',
    '**/coverage/**',
    'design_handoff_calebs_library/**',
    'mobile/**',
    // Regenerated by `npx convex codegen` on every deploy, and carries its own
    // eslint-disable directives. Linting it only ever produced noise about
    // "unused eslint-disable directive" warnings in files nobody hand-edits.
    'convex/_generated/**',
  ]),

  ...pluginVue.configs['flat/essential'],
  vueTsConfigs.recommended,

  ...pluginOxlint.buildFromOxlintConfigFile('.oxlintrc.json'),

  skipFormatting,

  {
    name: 'app/design-system-atoms',
    // Single-word atoms (Avatar, Icon, Stat, Ornament) are an established
    // project convention — renaming would churn every consumer. Last wins.
    rules: { 'vue/multi-word-component-names': 'off' },
  },
)
