#!/usr/bin/env python3
"""Extract the latin subsets from a Google Fonts css2 response, download the
woff2 files into public/fonts, and emit a local @font-face stylesheet.

Google serves these families as *variable* fonts, so the same file is returned
for every weight in the requested range (verified: 20 @font-face blocks collapse
to 8 distinct files). Emitting one @font-face per weight but pointing them all
at the single deduped file keeps the rendered result byte-identical to Google's
CSS while making the browser fetch each subset exactly once.
"""
import hashlib
import os
import re
import shutil
import urllib.request

SRC = "/tmp/opencode/gf.css"
OUT_DIR = "public/fonts"
OUT_CSS = "src/assets/fonts.css"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

css = open(SRC, encoding="utf-8").read()
os.makedirs(OUT_DIR, exist_ok=True)

blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
print(f"parsed {len(blocks)} blocks")

def field(block, name):
    m = re.search(rf"{name}:\s*([^;]+);", block)
    return m.group(1).strip() if m else None


def subset_of(urange):
    """Derive the subset from the unicode-range rather than trusting the
    /* ... */ comment. Google's comment labels and the ranges agree today, but
    the range is what actually governs whether the browser downloads the file,
    so it is the one worth keying filenames off."""
    if not urange:
        return None
    if urange.startswith("U+0000-00FF"):
        return "latin"
    if urange.startswith("U+0100-02BA"):
        return "latin-ext"
    return None


kept = []
for _, block in blocks:
    urange = field(block, "unicode-range")
    subset = subset_of(urange)
    if subset is None:
        continue
    family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
    kept.append({
        "subset": subset,
        "family": family,
        "style": field(block, "font-style") or "normal",
        "weight": field(block, "font-weight"),
        "url": re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1),
        "urange": urange,
    })

# ---- download + dedupe by content hash -------------------------------------
by_hash = {}
for face in kept:
    tmp = os.path.join(OUT_DIR, "_tmp.woff2")
    if not os.path.exists(tmp) or True:
        req = urllib.request.Request(face["url"], headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=60) as r:
            blob = r.read()
    digest = hashlib.sha256(blob).hexdigest()[:8]

    if digest not in by_hash:
        fam = face["family"].lower().replace(" ", "-")
        name = f"{fam}-{face['style']}-{face['subset']}-{digest}.woff2"
        with open(os.path.join(OUT_DIR, name), "wb") as fh:
            fh.write(blob)
        by_hash[digest] = name
        print(f"  {name:46s} {len(blob)/1024:7.1f} KB  "
              f"{face['family']} {face['style']} [{subset}]")
    face["file"] = by_hash[digest]

# Drop the un-deduped originals from the earlier run.
for f in os.listdir(OUT_DIR):
    if not f.endswith(".woff2"):
        continue
    if f not in by_hash.values():
        os.remove(os.path.join(OUT_DIR, f))
if os.path.exists(os.path.join(OUT_DIR, "_tmp.woff2")):
    os.remove(os.path.join(OUT_DIR, "_tmp.woff2"))

# ---- emit stylesheet -------------------------------------------------------
lines = [
    "/* Self-hosted webfonts.",
    " *",
    " * These used to load from a render-blocking <link> to fonts.googleapis.com.",
    " * That put two third-party origins (two DNS lookups + two TLS handshakes)",
    " * plus a 25 KB stylesheet in front of the first paint, and it applied to",
    " * every reader on a cold cache. Self-hosting removes both origins and gives",
    " * us control of font-display instead of Google's hardcoded 'swap'.",
    " *",
    " * Latin + latin-ext subsets only. Generated by tools/extract-fonts.py --",
    " * do not hand-edit, regenerate instead.",
    " *",
    " * These are variable fonts: one file serves every weight in the family, so",
    " * the four Inter weights below all resolve to the same 47 KB file and the",
    " * browser fetches it once.",
    " */",
    "",
]
for face in kept:
    lines += [
        "@font-face {",
        f"  font-family: '{face['family']}';",
        f"  font-style: {face['style']};",
        f"  font-weight: {face['weight']};",
        "  font-display: swap;",
        f"  src: url('/fonts/{face['file']}') format('woff2');",
    ]
    if face["urange"]:
        lines.append(f"  unicode-range: {face['urange']};")
    lines += ["}", ""]

os.makedirs(os.path.dirname(OUT_CSS), exist_ok=True)
with open(OUT_CSS, "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines))

# ---- preloads --------------------------------------------------------------
# An English page only ever fetches the *latin* blobs, and only three of them:
# one per family. Preloading those three covers every weight of every family,
# so the swap lands with the first paint instead of after it.
latin = {}
for face in kept:
    # Normal style only: the italic latin face is a separate file, and pulling
    # it would leave the headings (which are upright) waiting on a preload.
    if face["subset"] != "latin" or face["style"] != "normal":
        continue
    latin.setdefault(face["family"], face["file"])

order = ["Inter", "EB Garamond", "JetBrains Mono"]
print("\npreload (latin, one file per family, covers all weights):")
total = 0
for fam in order:
    f = latin[fam]
    size = os.path.getsize(os.path.join(OUT_DIR, f))
    total += size
    print(f"  {fam:16s} {f:46s} {size/1024:6.1f} KB")
print(f"  {'total':16s} {'':46s} {total/1024:6.1f} KB")
print("\nAdd a <link rel=preload> to index.html for each file above if the set "
      "has changed.")

print(f"\n{len(kept)} @font-face rules over {len(by_hash)} files "
      f"({total/1024:.1f} KB preloaded) -> {OUT_CSS}")